### ISSUE TITLE
mirror update over ssh fails

### ISSUE THREAD

**Issue by vdmkenny** [bachp/git-mirror#16]
My setup: Standard gitlab setup. Existing repositories in puppet/mirrors subgroup that I want to sync.
Token created, and seems valid. The application fails to push into my repo when using ssh. When using http, it seems to work, but then I have to manually enter my user credentials.

```
[root@gitlab git-mirror]# ./sync.sh 
START [2018-05-16 15:38:10.551361179 +02:00]: https://github.com/voxpupuli/puppet-fail2ban.git -> git@myserver.tld:puppet/mirrors/puppet-fail2ban.git
FAIL [2018-05-16 15:38:11.665388536 +02:00]: https://github.com/voxpupuli/puppet-fail2ban.git -> git@gitlab.myserver.tld:puppet/mirrors/puppet-fail2ban.git (Command "git" "push" "--mirror" "git@gitlab.myserver.tld:puppet/mirrors/puppet-fail2ban.git" failed with exist code: 128, Stderr: fatal: 'puppet/mirrors/puppet-fail2ban.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bachp** [comment]
Are you able to manually push to the repository?

**Comment by bachp** [comment]
The SSH urlnis comming from your gitlab instance. I would check if it is configured correctly and if you can push ans pull with the URL displayed by the gitlab UI.

**Comment by bachp** [comment]
@vdmkenny Have you been able to solve your problem? I will close the issue, please feel free to reopen.
