### ISSUE TITLE
new 'orchestrator' project around git-mirror

### ISSUE THREAD

**Issue by mhow2** [bachp/git-mirror#18]
Hi Pascal,
I didn't find any other communication channel to bring this information to you, so here it is.
I wrote a script tool at https://gitlab.ow2.org/ow2/gitlab-mirror-orchestrator
Basically it orchestrates Git repos mirroring using git-mirror in the background, ie, it takes a list of remote repos and spawn `git-mirror` to achieve the sync job.

I thought you and `git-mirror` users would be interested to know about it.
Regards,

**Comment by bachp** [comment]
@mhow2 Thanks for that. If you wish you can also do an MR adding a section about projects related to git-mirror.

**Comment by bachp** [comment]
As this is now in the Readme I will close this.
