### ISSUE TITLE
Create docker image containing git-mirror

### ISSUE THREAD

**Issue by bachp** [bachp/git-mirror#3]

**Comment by bachp** [comment]
The docker container is now available: https://hub.docker.com/r/bachp/git-mirror/ documentation needs to be updated.

**Comment by pquerner** [comment]
Is this considered OK?
```
sudo docker run -e GITLAB_PRIVATE_TOKEN="x" bachp/git-mirror -g mirror -u http://gitlab.example.com
```

**Comment by bachp** [comment]
I think that should work. However I'm thinking abiut changing the containers entrypoint so that it could be used easier in gitlab ci.

This would change the usage to:

```
docker run -e GITLAB_PRIVATE_TOKEN="x" bachp/git-mirror git-mirror -g mirror -u http://gitlab.example.com
```
