### ISSUE TITLE
Support recursive subgroups in GitLab

### ISSUE THREAD

**Issue by bachp** [bachp/git-mirror#4]
This makes it possible to structure repos in subgroups instead of a flat hirarchy

**Comment by bachp** [comment]
This depends on https://gitlab.com/gitlab-org/gitlab-ce/issues/40247 which will be released with Gitlab 10.3

**Comment by thuandt** [comment]
@bachp I saw PR is merged. How about implement this feature?

**Comment by bachp** [comment]
@thuandt This is actually aready implemented in 51f388f5bf79c5e254a1f5fe6980792332d8f0f8 which is in the [0.7.0](https://github.com/bachp/git-mirror/releases/tag/v0.7.0) release. I just forgot to update the issues.
