### ISSUE TITLE
v0.7.0 isn't backward compatible with gitlab's < 10.3

### ISSUE THREAD

**Issue by mhow2** [bachp/git-mirror#6]
Hi,
I just wanted to provide a feedback that git-mirror v0.7.0 is not backward compatible with gitlab < 10.3 because its API doesn't implement [sub-group](https://docs.gitlab.com/ce/api/groups.html#list-a-groups-39-s-subgroups)

PS: However v0.6.0 works like a charm
Cheers

**Comment by bachp** [comment]
Thanks for the feedback. I will have a look to see if i can do a more graceful fallback if the subgroup API is not available.
Also was planing to add a flag to disable the subgroup feature in case this is not wanted. But that should be independent of the gitlab version.
