### ISSUE TITLE
Repository has to be shared with group

### ISSUE THREAD

**Issue by pquerner** [bachp/git-mirror#7]
I think you failed to mention that the repository must be shared with the "mirror" group.

**Comment by bachp** [comment]
Do you mean that any repository shared with a group will be synced? If yes I was not aware of that "feature". Currently the assumption was that all projects in a group (*mirror* in the example) will get synced.

**Comment by pquerner** [comment]
Yes, if a previously existing repository is shared with the group "mirror", then this repository will be included in the update mechanism. Thats no writting in the README (installation).

I dont know what you mean by "all projects in a group". Isnt that what I mean? Are these two seperate things?

![image](https://user-images.githubusercontent.com/4364044/36950073-1ff40276-1ff1-11e8-8294-432fdd83d856.png)
(Settings > Member from a repository)

**Comment by bachp** [comment]
Yes you can create a repository inside a group eg. `mirror/my-project`, this is what I mean with all project within a group. You can also create a project in a different group eg. `other/foobar` and then share it with the `mirror` group, this would then still be part of the `other` group but would also be accessible to members of the `mirror` group.

**Comment by pquerner** [comment]
Ah yes, gotcha.

**Comment by bachp** [comment]
@pquerner I think your question is answered.
