### ISSUE TITLE
using 'skip: true' reports a YAML parsing error

### ISSUE THREAD

**Issue by mhow2** [bachp/git-mirror#80]
When I'm adding `skip: true` in project description, I get:

`[2021-06-04T07:33:16Z ERROR git_mirror] Error parsing YAML: Skip("https://gitlab....")`

Two things:
- Maybe it shouldn't be considered as an error, as it is configuration requested by the user
- As far as I understand, it's not a _parsing_ error.

**Comment by bachp** [comment]
@mhow2 The descritpion needs to be valid YAML.

So something like:

```
origin: https://git.example.org/my-project.git
skip: true
```
Should work. Newline and indentian are important.

**Comment by mhow2** [comment]
I get the same output with the exact example description you provided. Do I miss something ?

**Comment by bachp** [comment]
@mhow2 I checked the code and this is really an issue with the error reporting. The skip mechanism works, but it is interpreted as any other mirror error.
