### ISSUE TITLE
How can I disable certificate check?

### ISSUE THREAD

**Issue by guimaluf** [bachp/git-mirror#9]
I tried to run with docker and also with local compiled binary, with both I get this error:

```
2018-03-16T10:42:07-03:00 - DEBUG - Git executable: "git"
2018-03-16T10:42:07-03:00 - WARN - Unable to get subgroups: Unable to connect to: https://git.rnp.br/api/v4/groups/edudrive/subgroups?per_page=100&page=1 (invalid certificate: UnknownIssuer)
2018-03-16T10:42:07-03:00 - ERROR - Error occured: Unable to get mirror repos (Unable to connect to: https://git.rnp.br/api/v4/groups/edudrive/projects?per_page=100&page=1 (invalid certificate: UnknownIssuer))
```

I realized that is a certificate issue
```
depth=0 C = BR, ST = RJ, L = Rio de Janeiro, O = REDE NACIONAL DE ENSINO E PESQUISA - RNP, CN = git.rnp.br
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = BR, ST = RJ, L = Rio de Janeiro, O = REDE NACIONAL DE ENSINO E PESQUISA - RNP, CN = git.rnp.br
verify error:num=21:unable to verify the first certificate
verify return:1
```

I know nothing about rust and  I would like to disable SSL/certificate verification. How can I achieve this? :)

Thanks for this awesome initiative, I was looking for something like this for a while!

**Comment by bachp** [comment]
The docker container is based on Debian 9 and it seems the included truststore doesn't include the root certificate used to sign the above certificate.

Currently there is no way to disable the certificate check but I think it might be a good idea to add one.
Also an option to add custom CA root certificates might be useful.

I will see what I can do.

**Comment by guimaluf** [comment]
@bachp any workaround can do to bypass thoses checks?

**Comment by bachp** [comment]
@guimaluf Unfortunately, none that I'm aware of.

**Comment by bachp** [comment]
It seems disabbling ssl checks is currently not possible at all.
Even if the feature becomes available I will need to do the refactoring to move to hyper 0.11.

So not sure what can be done at the moment.

**Comment by guimaluf** [comment]
Seems easier to fix the certificate instead of ignoring all checks! :)
thank you @bachp !
